import React, { useState } from "react";
import Head from "next/head";
import { SearchResultField } from "@/components/SearchResultFeild";
import SearchForm from "@/components/SearchForm";

export default function Home() {
  const [inputValue, setInputValue] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchForm setInputValue={setInputValue} />
      <SearchResultField inputValue={inputValue} />
    </>
  );
}
